version: "3.8"

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: geo_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: geodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d geodb"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: .
    container_name: fastapi_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/geodb
      ACCESS_TOKEN_EXPIRE_MINUTES: 2880
    ports:
      - "8000:8000"
    volumes:
    - .:/app
    command: ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]

volumes:
  postgres_data:
